# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-16 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
    ]
