# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-16 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0006_person_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='result',
            field=models.IntegerField(default=0),
        ),
    ]
