# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0008_auto_20180517_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='result1',
            new_name='result',
        ),
    ]
