# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-01 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=127)),
                ('nAnswers', models.IntegerField(default=3)),
                ('answer1', models.CharField(max_length=127)),
                ('answer2', models.CharField(max_length=127)),
                ('answer3', models.CharField(max_length=127)),
                ('rightAnswer', models.IntegerField(default=1)),
                ('ageMin', models.IntegerField(default=0)),
                ('ageMax', models.IntegerField(default=100)),
                ('choice', models.IntegerField(default=100)),
            ],
        ),
    ]
